In [9]:
import numpy as np
def symmetric_matrix(A):
    if(A.all()==A.T.all()):
        return print('B is a symmetric matrix')
    else:
        return print('B is not a symmnetric matrix')
def skew_symmetric_matrix(A):
    if(A.all()==(-1)*(A.T).all()):
        return print('C is a skew symmetric matrix')
    else:
        return print('C is not a skew symmetric matrix')
def equal_matrices(A,B):
    if(A.all()==B.all()):
        return print('A and D are equal matrices')
    else:
        return print('A and D are not equal matrices')
# A is the givent matrix
A=np.array([[6,-2,2],[-2,3,-1],[2,-1,3]])
#B be the symmetric matrix
B=(A+A.T)/2
print('B is',B)
#checking for matrix to be symmetric
symmetric_matrix(B)
#C be the skew symmetric matrix
C=(A-(A.T))/2
print('C is',C)
#checking for matrix to be skew symmetric
skew_symmetric_matrix(C)
#Adding symmetric and skew symmetric matrices
D=B+C
print('D is',D)
#comparing original matrix and sum of symmetric and skew symmetric matrices
equal_matrices(A,D)
#D is the sum of symmetric matrix B and a skew symmetric matrix C

B is [[ 6. -2.  2.]
 [-2.  3. -1.]
 [ 2. -1.  3.]]
B is a symmetric matrix
C is [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
C is a skew symmetric matrix
D is [[ 6. -2.  2.]
 [-2.  3. -1.]
 [ 2. -1.  3.]]
A and D are equal matrices
